# Generated by Django 4.1.4 on 2026-08-18 18:29

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    
    expense_categories = [
        'Food & Dining', 
        'Transportation', 
        'Shopping', 
        'Entertainment', 
        'Housing', 
        'Utilities', 
        'Healthcare', 
        'Education', 
        'Personal Care', 
        'Miscellaneous'
    ]
    
    income_categories = [
        'Salary', 
        'Business', 
        'Freelance', 
        'Investments', 
        'Gifts', 
        'Refunds', 
        'Other Income'
    ]

    for cat_name in expense_categories:
        Category.objects.get_or_create(
            name=cat_name,
            type='expense',
            is_default=True,
            user=None
        )
        
    for cat_name in income_categories:
        Category.objects.get_or_create(
            name=cat_name,
            type='income',
            is_default=True,
            user=None
        )

def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    Category.objects.filter(is_default=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
