/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-error': 'var(--color-on-error)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        primary: 'var(--color-primary)',
        background: 'var(--color-background)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-bright': 'var(--color-surface-bright)',
        'outline-variant': 'var(--color-outline-variant)',
        'primary-container': 'var(--color-primary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-tint': 'var(--color-surface-tint)',
        'inverse-surface': 'var(--color-inverse-surface)',
        error: 'var(--color-error)',
        outline: 'var(--color-outline)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-background': 'var(--color-on-background)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'error-container': 'var(--color-error-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-surface': 'var(--color-on-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        surface: 'var(--color-surface)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-primary': 'var(--color-on-primary)',
        'surface-dim': 'var(--color-surface-dim)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        secondary: 'var(--color-secondary)',
        'on-error-container': 'var(--color-on-error-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '40px',
        base: '8px',
        xs: '4px',
        md: '16px',
        'container-max': '1200px',
        lg: '24px',
        gutter: '24px',
        sm: '12px',
      },
      fontFamily: {
        'headline-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'label-md': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        display: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
